#ifndef FORMAT_H
#define FORMAT_H

#define VERBOSE 1

#define RS_FRAME_WIDTH 1280 //1280 //640
#define RS_FRAME_HEIGHT 720 //720 //480
#define RS_FRAME_RATE 15 //15 //30
#define RS_FRAME_PERIOD 1000/RS_FRAME_RATE
#define RS_FRAME_SIZE RS_FRAME_WIDTH * RS_FRAME_HEIGHT

#define CV_FRAME_WIDTH 1280  //1600
#define CV_FRAME_HEIGHT 720 //1200
#define CV_FRAME_RATE 10 //5

#define CONV_DELAY RS_FRAME_PERIOD/2 // rs2 to pcl converter race condition
#define PROC_DELAY CONV_DELAY
#define SEG_DELAY 100

#define POINT_BUF_SIZE 100
#define CLOUD_BUF_SIZE 100
#define MAT_BUF_SIZE 100
#define CAP_BUF_SIZE 100
#define TOBJ_BUF_SIZE 100

#define REF_PIXEL 60
#define REF_SIZE_MM 26

//#define IMSHOW_CAP
//#define IMSHOW_SEG

#endif // FORMAT_H
